### ISSUE TITLE
Create MainPage Component

### ISSUE THREAD

**Issue by zoeyourlife** [energizer-develop/Y_FE_WIKI#2]
## 설명
- 메인페이지를 만듭니다.

## 할 일

- [x] 캐로셀을 활용한 공지사항 배너 만들기
- [ ] Wiki 소개문 컴포넌트 구성
- [ ] Lottie를 활용한 애니메이션 
- [ ] 아날로그 시계 구현 (선택사항) (추후 상황에 따라 변동)
- 아날로그 시계는 어떤 식의 모션을 보여줄 지 아직 정해지지 않음 
- ex) 현재 시간 띄우기 , 통근 시간 || 경과시간 띄우기 상의 中

**Comment by gahyuun** [comment]
아날로그 시계는 저희 상황에 따라 추후에 혹시 바뀔지도 모르니까 선택 사항으로 구현해주시면 더 좋을 것 같아요!

**Comment by zoeyourlife** [comment]
> 아날로그 시계는 저희 상황에 따라 추후에 혹시 바뀔지도 모르니까 선택 사항으로 구현해주시면 더 좋을 것 같아요!

넵 변경해두었습니다.
